# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daiarineko/standalone-projects/NekoMino

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daiarineko/standalone-projects/NekoMino

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daiarineko/standalone-projects/NekoMino/CMakeFiles /home/daiarineko/standalone-projects/NekoMino//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daiarineko/standalone-projects/NekoMino/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nekomino

# Build rule for target.
nekomino: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nekomino
.PHONY : nekomino

# fast build rule for target.
nekomino/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/build
.PHONY : nekomino/fast

#=============================================================================
# Target rules for targets named debug

# Build rule for target.
debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 debug
.PHONY : debug

# fast build rule for target.
debug/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/build
.PHONY : debug/fast

#=============================================================================
# Target rules for targets named release

# Build rule for target.
release: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 release
.PHONY : release

# fast build rule for target.
release/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/release.dir/build.make CMakeFiles/release.dir/build
.PHONY : release/fast

src/error_handling.o: src/error_handling.cpp.o
.PHONY : src/error_handling.o

# target to build an object file
src/error_handling.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/error_handling.cpp.o
.PHONY : src/error_handling.cpp.o

src/error_handling.i: src/error_handling.cpp.i
.PHONY : src/error_handling.i

# target to preprocess a source file
src/error_handling.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/error_handling.cpp.i
.PHONY : src/error_handling.cpp.i

src/error_handling.s: src/error_handling.cpp.s
.PHONY : src/error_handling.s

# target to generate assembly for a file
src/error_handling.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/error_handling.cpp.s
.PHONY : src/error_handling.cpp.s

src/localization.o: src/localization.cpp.o
.PHONY : src/localization.o

# target to build an object file
src/localization.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/localization.cpp.o
.PHONY : src/localization.cpp.o

src/localization.i: src/localization.cpp.i
.PHONY : src/localization.i

# target to preprocess a source file
src/localization.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/localization.cpp.i
.PHONY : src/localization.cpp.i

src/localization.s: src/localization.cpp.s
.PHONY : src/localization.s

# target to generate assembly for a file
src/localization.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/localization.cpp.s
.PHONY : src/localization.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/tetris_core/board.o: src/tetris_core/board.cpp.o
.PHONY : src/tetris_core/board.o

# target to build an object file
src/tetris_core/board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/tetris_core/board.cpp.o
.PHONY : src/tetris_core/board.cpp.o

src/tetris_core/board.i: src/tetris_core/board.cpp.i
.PHONY : src/tetris_core/board.i

# target to preprocess a source file
src/tetris_core/board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/tetris_core/board.cpp.i
.PHONY : src/tetris_core/board.cpp.i

src/tetris_core/board.s: src/tetris_core/board.cpp.s
.PHONY : src/tetris_core/board.s

# target to generate assembly for a file
src/tetris_core/board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/tetris_core/board.cpp.s
.PHONY : src/tetris_core/board.cpp.s

src/tetris_core/core.o: src/tetris_core/core.cpp.o
.PHONY : src/tetris_core/core.o

# target to build an object file
src/tetris_core/core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/tetris_core/core.cpp.o
.PHONY : src/tetris_core/core.cpp.o

src/tetris_core/core.i: src/tetris_core/core.cpp.i
.PHONY : src/tetris_core/core.i

# target to preprocess a source file
src/tetris_core/core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/tetris_core/core.cpp.i
.PHONY : src/tetris_core/core.cpp.i

src/tetris_core/core.s: src/tetris_core/core.cpp.s
.PHONY : src/tetris_core/core.s

# target to generate assembly for a file
src/tetris_core/core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/tetris_core/core.cpp.s
.PHONY : src/tetris_core/core.cpp.s

src/tetris_core/minoes.o: src/tetris_core/minoes.cpp.o
.PHONY : src/tetris_core/minoes.o

# target to build an object file
src/tetris_core/minoes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/tetris_core/minoes.cpp.o
.PHONY : src/tetris_core/minoes.cpp.o

src/tetris_core/minoes.i: src/tetris_core/minoes.cpp.i
.PHONY : src/tetris_core/minoes.i

# target to preprocess a source file
src/tetris_core/minoes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/tetris_core/minoes.cpp.i
.PHONY : src/tetris_core/minoes.cpp.i

src/tetris_core/minoes.s: src/tetris_core/minoes.cpp.s
.PHONY : src/tetris_core/minoes.s

# target to generate assembly for a file
src/tetris_core/minoes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/tetris_core/minoes.cpp.s
.PHONY : src/tetris_core/minoes.cpp.s

src/tetris_core/rs.o: src/tetris_core/rs.cpp.o
.PHONY : src/tetris_core/rs.o

# target to build an object file
src/tetris_core/rs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/tetris_core/rs.cpp.o
.PHONY : src/tetris_core/rs.cpp.o

src/tetris_core/rs.i: src/tetris_core/rs.cpp.i
.PHONY : src/tetris_core/rs.i

# target to preprocess a source file
src/tetris_core/rs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/tetris_core/rs.cpp.i
.PHONY : src/tetris_core/rs.cpp.i

src/tetris_core/rs.s: src/tetris_core/rs.cpp.s
.PHONY : src/tetris_core/rs.s

# target to generate assembly for a file
src/tetris_core/rs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/tetris_core/rs.cpp.s
.PHONY : src/tetris_core/rs.cpp.s

src/ui_core/interface.o: src/ui_core/interface.cpp.o
.PHONY : src/ui_core/interface.o

# target to build an object file
src/ui_core/interface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/ui_core/interface.cpp.o
.PHONY : src/ui_core/interface.cpp.o

src/ui_core/interface.i: src/ui_core/interface.cpp.i
.PHONY : src/ui_core/interface.i

# target to preprocess a source file
src/ui_core/interface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/ui_core/interface.cpp.i
.PHONY : src/ui_core/interface.cpp.i

src/ui_core/interface.s: src/ui_core/interface.cpp.s
.PHONY : src/ui_core/interface.s

# target to generate assembly for a file
src/ui_core/interface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nekomino.dir/build.make CMakeFiles/nekomino.dir/src/ui_core/interface.cpp.s
.PHONY : src/ui_core/interface.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... debug"
	@echo "... release"
	@echo "... nekomino"
	@echo "... src/error_handling.o"
	@echo "... src/error_handling.i"
	@echo "... src/error_handling.s"
	@echo "... src/localization.o"
	@echo "... src/localization.i"
	@echo "... src/localization.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/tetris_core/board.o"
	@echo "... src/tetris_core/board.i"
	@echo "... src/tetris_core/board.s"
	@echo "... src/tetris_core/core.o"
	@echo "... src/tetris_core/core.i"
	@echo "... src/tetris_core/core.s"
	@echo "... src/tetris_core/minoes.o"
	@echo "... src/tetris_core/minoes.i"
	@echo "... src/tetris_core/minoes.s"
	@echo "... src/tetris_core/rs.o"
	@echo "... src/tetris_core/rs.i"
	@echo "... src/tetris_core/rs.s"
	@echo "... src/ui_core/interface.o"
	@echo "... src/ui_core/interface.i"
	@echo "... src/ui_core/interface.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

