# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = G:\winlibs-x86_64-posix-seh-gcc-14.2.0-mingw-w64ucrt-12.0.0-r2\mingw64\bin\cmake.exe

# The command to remove a file.
RM = G:\winlibs-x86_64-posix-seh-gcc-14.2.0-mingw-w64ucrt-12.0.0-r2\mingw64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = G:\Projects\NekoMino\NekoMino

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = G:\Projects\NekoMino\NekoMino

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	G:\winlibs-x86_64-posix-seh-gcc-14.2.0-mingw-w64ucrt-12.0.0-r2\mingw64\bin\cmake.exe -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	G:\winlibs-x86_64-posix-seh-gcc-14.2.0-mingw-w64ucrt-12.0.0-r2\mingw64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start G:\Projects\NekoMino\NekoMino\CMakeFiles G:\Projects\NekoMino\NekoMino\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start G:\Projects\NekoMino\NekoMino\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nekomino

# Build rule for target.
nekomino: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 nekomino
.PHONY : nekomino

# fast build rule for target.
nekomino/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/build
.PHONY : nekomino/fast

#=============================================================================
# Target rules for targets named debug

# Build rule for target.
debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 debug
.PHONY : debug

# fast build rule for target.
debug/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\debug.dir\build.make CMakeFiles/debug.dir/build
.PHONY : debug/fast

#=============================================================================
# Target rules for targets named release

# Build rule for target.
release: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 release
.PHONY : release

# fast build rule for target.
release/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\release.dir\build.make CMakeFiles/release.dir/build
.PHONY : release/fast

src/config/config.obj: src/config/config.cpp.obj
.PHONY : src/config/config.obj

# target to build an object file
src/config/config.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/config/config.cpp.obj
.PHONY : src/config/config.cpp.obj

src/config/config.i: src/config/config.cpp.i
.PHONY : src/config/config.i

# target to preprocess a source file
src/config/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/config/config.cpp.i
.PHONY : src/config/config.cpp.i

src/config/config.s: src/config/config.cpp.s
.PHONY : src/config/config.s

# target to generate assembly for a file
src/config/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/config/config.cpp.s
.PHONY : src/config/config.cpp.s

src/config/config_defaults.obj: src/config/config_defaults.cpp.obj
.PHONY : src/config/config_defaults.obj

# target to build an object file
src/config/config_defaults.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/config/config_defaults.cpp.obj
.PHONY : src/config/config_defaults.cpp.obj

src/config/config_defaults.i: src/config/config_defaults.cpp.i
.PHONY : src/config/config_defaults.i

# target to preprocess a source file
src/config/config_defaults.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/config/config_defaults.cpp.i
.PHONY : src/config/config_defaults.cpp.i

src/config/config_defaults.s: src/config/config_defaults.cpp.s
.PHONY : src/config/config_defaults.s

# target to generate assembly for a file
src/config/config_defaults.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/config/config_defaults.cpp.s
.PHONY : src/config/config_defaults.cpp.s

src/config/config_io.obj: src/config/config_io.cpp.obj
.PHONY : src/config/config_io.obj

# target to build an object file
src/config/config_io.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/config/config_io.cpp.obj
.PHONY : src/config/config_io.cpp.obj

src/config/config_io.i: src/config/config_io.cpp.i
.PHONY : src/config/config_io.i

# target to preprocess a source file
src/config/config_io.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/config/config_io.cpp.i
.PHONY : src/config/config_io.cpp.i

src/config/config_io.s: src/config/config_io.cpp.s
.PHONY : src/config/config_io.s

# target to generate assembly for a file
src/config/config_io.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/config/config_io.cpp.s
.PHONY : src/config/config_io.cpp.s

src/config/config_validate.obj: src/config/config_validate.cpp.obj
.PHONY : src/config/config_validate.obj

# target to build an object file
src/config/config_validate.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/config/config_validate.cpp.obj
.PHONY : src/config/config_validate.cpp.obj

src/config/config_validate.i: src/config/config_validate.cpp.i
.PHONY : src/config/config_validate.i

# target to preprocess a source file
src/config/config_validate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/config/config_validate.cpp.i
.PHONY : src/config/config_validate.cpp.i

src/config/config_validate.s: src/config/config_validate.cpp.s
.PHONY : src/config/config_validate.s

# target to generate assembly for a file
src/config/config_validate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/config/config_validate.cpp.s
.PHONY : src/config/config_validate.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/tetris_core/board.obj: src/tetris_core/board.cpp.obj
.PHONY : src/tetris_core/board.obj

# target to build an object file
src/tetris_core/board.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/tetris_core/board.cpp.obj
.PHONY : src/tetris_core/board.cpp.obj

src/tetris_core/board.i: src/tetris_core/board.cpp.i
.PHONY : src/tetris_core/board.i

# target to preprocess a source file
src/tetris_core/board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/tetris_core/board.cpp.i
.PHONY : src/tetris_core/board.cpp.i

src/tetris_core/board.s: src/tetris_core/board.cpp.s
.PHONY : src/tetris_core/board.s

# target to generate assembly for a file
src/tetris_core/board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/tetris_core/board.cpp.s
.PHONY : src/tetris_core/board.cpp.s

src/tetris_core/core.obj: src/tetris_core/core.cpp.obj
.PHONY : src/tetris_core/core.obj

# target to build an object file
src/tetris_core/core.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/tetris_core/core.cpp.obj
.PHONY : src/tetris_core/core.cpp.obj

src/tetris_core/core.i: src/tetris_core/core.cpp.i
.PHONY : src/tetris_core/core.i

# target to preprocess a source file
src/tetris_core/core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/tetris_core/core.cpp.i
.PHONY : src/tetris_core/core.cpp.i

src/tetris_core/core.s: src/tetris_core/core.cpp.s
.PHONY : src/tetris_core/core.s

# target to generate assembly for a file
src/tetris_core/core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/tetris_core/core.cpp.s
.PHONY : src/tetris_core/core.cpp.s

src/tetris_core/minoes.obj: src/tetris_core/minoes.cpp.obj
.PHONY : src/tetris_core/minoes.obj

# target to build an object file
src/tetris_core/minoes.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/tetris_core/minoes.cpp.obj
.PHONY : src/tetris_core/minoes.cpp.obj

src/tetris_core/minoes.i: src/tetris_core/minoes.cpp.i
.PHONY : src/tetris_core/minoes.i

# target to preprocess a source file
src/tetris_core/minoes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/tetris_core/minoes.cpp.i
.PHONY : src/tetris_core/minoes.cpp.i

src/tetris_core/minoes.s: src/tetris_core/minoes.cpp.s
.PHONY : src/tetris_core/minoes.s

# target to generate assembly for a file
src/tetris_core/minoes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/tetris_core/minoes.cpp.s
.PHONY : src/tetris_core/minoes.cpp.s

src/tetris_core/rs.obj: src/tetris_core/rs.cpp.obj
.PHONY : src/tetris_core/rs.obj

# target to build an object file
src/tetris_core/rs.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/tetris_core/rs.cpp.obj
.PHONY : src/tetris_core/rs.cpp.obj

src/tetris_core/rs.i: src/tetris_core/rs.cpp.i
.PHONY : src/tetris_core/rs.i

# target to preprocess a source file
src/tetris_core/rs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/tetris_core/rs.cpp.i
.PHONY : src/tetris_core/rs.cpp.i

src/tetris_core/rs.s: src/tetris_core/rs.cpp.s
.PHONY : src/tetris_core/rs.s

# target to generate assembly for a file
src/tetris_core/rs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/tetris_core/rs.cpp.s
.PHONY : src/tetris_core/rs.cpp.s

src/ui_core/interface.obj: src/ui_core/interface.cpp.obj
.PHONY : src/ui_core/interface.obj

# target to build an object file
src/ui_core/interface.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/ui_core/interface.cpp.obj
.PHONY : src/ui_core/interface.cpp.obj

src/ui_core/interface.i: src/ui_core/interface.cpp.i
.PHONY : src/ui_core/interface.i

# target to preprocess a source file
src/ui_core/interface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/ui_core/interface.cpp.i
.PHONY : src/ui_core/interface.cpp.i

src/ui_core/interface.s: src/ui_core/interface.cpp.s
.PHONY : src/ui_core/interface.s

# target to generate assembly for a file
src/ui_core/interface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/ui_core/interface.cpp.s
.PHONY : src/ui_core/interface.cpp.s

src/util/error_handling.obj: src/util/error_handling.cpp.obj
.PHONY : src/util/error_handling.obj

# target to build an object file
src/util/error_handling.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/util/error_handling.cpp.obj
.PHONY : src/util/error_handling.cpp.obj

src/util/error_handling.i: src/util/error_handling.cpp.i
.PHONY : src/util/error_handling.i

# target to preprocess a source file
src/util/error_handling.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/util/error_handling.cpp.i
.PHONY : src/util/error_handling.cpp.i

src/util/error_handling.s: src/util/error_handling.cpp.s
.PHONY : src/util/error_handling.s

# target to generate assembly for a file
src/util/error_handling.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/util/error_handling.cpp.s
.PHONY : src/util/error_handling.cpp.s

src/util/localization.obj: src/util/localization.cpp.obj
.PHONY : src/util/localization.obj

# target to build an object file
src/util/localization.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/util/localization.cpp.obj
.PHONY : src/util/localization.cpp.obj

src/util/localization.i: src/util/localization.cpp.i
.PHONY : src/util/localization.i

# target to preprocess a source file
src/util/localization.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/util/localization.cpp.i
.PHONY : src/util/localization.cpp.i

src/util/localization.s: src/util/localization.cpp.s
.PHONY : src/util/localization.s

# target to generate assembly for a file
src/util/localization.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\nekomino.dir\build.make CMakeFiles/nekomino.dir/src/util/localization.cpp.s
.PHONY : src/util/localization.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... debug
	@echo ... release
	@echo ... nekomino
	@echo ... src/config/config.obj
	@echo ... src/config/config.i
	@echo ... src/config/config.s
	@echo ... src/config/config_defaults.obj
	@echo ... src/config/config_defaults.i
	@echo ... src/config/config_defaults.s
	@echo ... src/config/config_io.obj
	@echo ... src/config/config_io.i
	@echo ... src/config/config_io.s
	@echo ... src/config/config_validate.obj
	@echo ... src/config/config_validate.i
	@echo ... src/config/config_validate.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/tetris_core/board.obj
	@echo ... src/tetris_core/board.i
	@echo ... src/tetris_core/board.s
	@echo ... src/tetris_core/core.obj
	@echo ... src/tetris_core/core.i
	@echo ... src/tetris_core/core.s
	@echo ... src/tetris_core/minoes.obj
	@echo ... src/tetris_core/minoes.i
	@echo ... src/tetris_core/minoes.s
	@echo ... src/tetris_core/rs.obj
	@echo ... src/tetris_core/rs.i
	@echo ... src/tetris_core/rs.s
	@echo ... src/ui_core/interface.obj
	@echo ... src/ui_core/interface.i
	@echo ... src/ui_core/interface.s
	@echo ... src/util/error_handling.obj
	@echo ... src/util/error_handling.i
	@echo ... src/util/error_handling.s
	@echo ... src/util/localization.obj
	@echo ... src/util/localization.i
	@echo ... src/util/localization.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

